// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package spaceship

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SpaceshipServiceClient is the client API for SpaceshipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpaceshipServiceClient interface {
	CreateSpaceship(ctx context.Context, in *CreateSpaceshipRequest, opts ...grpc.CallOption) (*CreateSpaceshipResponse, error)
	GetSpaceships(ctx context.Context, in *GetSpaceshipsRequest, opts ...grpc.CallOption) (*GetSpaceshipsResponse, error)
	GetSpaceship(ctx context.Context, in *GetSpaceshipRequest, opts ...grpc.CallOption) (*GetSpaceshipResponse, error)
	UpdateSpaceship(ctx context.Context, in *UpdateSpaceshipRequest, opts ...grpc.CallOption) (*UpdateSpaceshipResponse, error)
	DeleteSpaceship(ctx context.Context, in *DeleteSpaceshipRequest, opts ...grpc.CallOption) (*DeleteSpaceshipResponse, error)
}

type spaceshipServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpaceshipServiceClient(cc grpc.ClientConnInterface) SpaceshipServiceClient {
	return &spaceshipServiceClient{cc}
}

func (c *spaceshipServiceClient) CreateSpaceship(ctx context.Context, in *CreateSpaceshipRequest, opts ...grpc.CallOption) (*CreateSpaceshipResponse, error) {
	out := new(CreateSpaceshipResponse)
	err := c.cc.Invoke(ctx, "/spaceship.SpaceshipService/CreateSpaceship", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceshipServiceClient) GetSpaceships(ctx context.Context, in *GetSpaceshipsRequest, opts ...grpc.CallOption) (*GetSpaceshipsResponse, error) {
	out := new(GetSpaceshipsResponse)
	err := c.cc.Invoke(ctx, "/spaceship.SpaceshipService/GetSpaceships", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceshipServiceClient) GetSpaceship(ctx context.Context, in *GetSpaceshipRequest, opts ...grpc.CallOption) (*GetSpaceshipResponse, error) {
	out := new(GetSpaceshipResponse)
	err := c.cc.Invoke(ctx, "/spaceship.SpaceshipService/GetSpaceship", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceshipServiceClient) UpdateSpaceship(ctx context.Context, in *UpdateSpaceshipRequest, opts ...grpc.CallOption) (*UpdateSpaceshipResponse, error) {
	out := new(UpdateSpaceshipResponse)
	err := c.cc.Invoke(ctx, "/spaceship.SpaceshipService/UpdateSpaceship", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceshipServiceClient) DeleteSpaceship(ctx context.Context, in *DeleteSpaceshipRequest, opts ...grpc.CallOption) (*DeleteSpaceshipResponse, error) {
	out := new(DeleteSpaceshipResponse)
	err := c.cc.Invoke(ctx, "/spaceship.SpaceshipService/DeleteSpaceship", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpaceshipServiceServer is the server API for SpaceshipService service.
// All implementations should embed UnimplementedSpaceshipServiceServer
// for forward compatibility
type SpaceshipServiceServer interface {
	CreateSpaceship(context.Context, *CreateSpaceshipRequest) (*CreateSpaceshipResponse, error)
	GetSpaceships(context.Context, *GetSpaceshipsRequest) (*GetSpaceshipsResponse, error)
	GetSpaceship(context.Context, *GetSpaceshipRequest) (*GetSpaceshipResponse, error)
	UpdateSpaceship(context.Context, *UpdateSpaceshipRequest) (*UpdateSpaceshipResponse, error)
	DeleteSpaceship(context.Context, *DeleteSpaceshipRequest) (*DeleteSpaceshipResponse, error)
}

// UnimplementedSpaceshipServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSpaceshipServiceServer struct {
}

func (UnimplementedSpaceshipServiceServer) CreateSpaceship(context.Context, *CreateSpaceshipRequest) (*CreateSpaceshipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSpaceship not implemented")
}
func (UnimplementedSpaceshipServiceServer) GetSpaceships(context.Context, *GetSpaceshipsRequest) (*GetSpaceshipsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpaceships not implemented")
}
func (UnimplementedSpaceshipServiceServer) GetSpaceship(context.Context, *GetSpaceshipRequest) (*GetSpaceshipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpaceship not implemented")
}
func (UnimplementedSpaceshipServiceServer) UpdateSpaceship(context.Context, *UpdateSpaceshipRequest) (*UpdateSpaceshipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSpaceship not implemented")
}
func (UnimplementedSpaceshipServiceServer) DeleteSpaceship(context.Context, *DeleteSpaceshipRequest) (*DeleteSpaceshipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSpaceship not implemented")
}

// UnsafeSpaceshipServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpaceshipServiceServer will
// result in compilation errors.
type UnsafeSpaceshipServiceServer interface {
	mustEmbedUnimplementedSpaceshipServiceServer()
}

func RegisterSpaceshipServiceServer(s grpc.ServiceRegistrar, srv SpaceshipServiceServer) {
	s.RegisterService(&SpaceshipService_ServiceDesc, srv)
}

func _SpaceshipService_CreateSpaceship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSpaceshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceshipServiceServer).CreateSpaceship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spaceship.SpaceshipService/CreateSpaceship",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceshipServiceServer).CreateSpaceship(ctx, req.(*CreateSpaceshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceshipService_GetSpaceships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpaceshipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceshipServiceServer).GetSpaceships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spaceship.SpaceshipService/GetSpaceships",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceshipServiceServer).GetSpaceships(ctx, req.(*GetSpaceshipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceshipService_GetSpaceship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpaceshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceshipServiceServer).GetSpaceship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spaceship.SpaceshipService/GetSpaceship",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceshipServiceServer).GetSpaceship(ctx, req.(*GetSpaceshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceshipService_UpdateSpaceship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSpaceshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceshipServiceServer).UpdateSpaceship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spaceship.SpaceshipService/UpdateSpaceship",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceshipServiceServer).UpdateSpaceship(ctx, req.(*UpdateSpaceshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceshipService_DeleteSpaceship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSpaceshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceshipServiceServer).DeleteSpaceship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spaceship.SpaceshipService/DeleteSpaceship",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceshipServiceServer).DeleteSpaceship(ctx, req.(*DeleteSpaceshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpaceshipService_ServiceDesc is the grpc.ServiceDesc for SpaceshipService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpaceshipService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spaceship.SpaceshipService",
	HandlerType: (*SpaceshipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSpaceship",
			Handler:    _SpaceshipService_CreateSpaceship_Handler,
		},
		{
			MethodName: "GetSpaceships",
			Handler:    _SpaceshipService_GetSpaceships_Handler,
		},
		{
			MethodName: "GetSpaceship",
			Handler:    _SpaceshipService_GetSpaceship_Handler,
		},
		{
			MethodName: "UpdateSpaceship",
			Handler:    _SpaceshipService_UpdateSpaceship_Handler,
		},
		{
			MethodName: "DeleteSpaceship",
			Handler:    _SpaceshipService_DeleteSpaceship_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/spaceship.proto",
}
