// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: grpc/spaceship.proto

package spaceship

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSpaceshipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string                             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Class    string                             `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	Crew     int64                              `protobuf:"varint,3,opt,name=crew,proto3" json:"crew,omitempty"`
	ImageUrl string                             `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Value    float64                            `protobuf:"fixed64,5,opt,name=value,proto3" json:"value,omitempty"`
	Status   string                             `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Armament []*CreateSpaceshipRequest_Armament `protobuf:"bytes,7,rep,name=armament,proto3" json:"armament,omitempty"`
}

func (x *CreateSpaceshipRequest) Reset() {
	*x = CreateSpaceshipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_spaceship_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSpaceshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpaceshipRequest) ProtoMessage() {}

func (x *CreateSpaceshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_spaceship_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpaceshipRequest.ProtoReflect.Descriptor instead.
func (*CreateSpaceshipRequest) Descriptor() ([]byte, []int) {
	return file_grpc_spaceship_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSpaceshipRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSpaceshipRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *CreateSpaceshipRequest) GetCrew() int64 {
	if x != nil {
		return x.Crew
	}
	return 0
}

func (x *CreateSpaceshipRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreateSpaceshipRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CreateSpaceshipRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateSpaceshipRequest) GetArmament() []*CreateSpaceshipRequest_Armament {
	if x != nil {
		return x.Armament
	}
	return nil
}

type CreateSpaceshipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spaceship *Spaceship `protobuf:"bytes,1,opt,name=spaceship,proto3" json:"spaceship,omitempty"`
}

func (x *CreateSpaceshipResponse) Reset() {
	*x = CreateSpaceshipResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_spaceship_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSpaceshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpaceshipResponse) ProtoMessage() {}

func (x *CreateSpaceshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_spaceship_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpaceshipResponse.ProtoReflect.Descriptor instead.
func (*CreateSpaceshipResponse) Descriptor() ([]byte, []int) {
	return file_grpc_spaceship_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSpaceshipResponse) GetSpaceship() *Spaceship {
	if x != nil {
		return x.Spaceship
	}
	return nil
}

type GetSpaceshipsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Class  string `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetSpaceshipsRequest) Reset() {
	*x = GetSpaceshipsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_spaceship_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpaceshipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpaceshipsRequest) ProtoMessage() {}

func (x *GetSpaceshipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_spaceship_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpaceshipsRequest.ProtoReflect.Descriptor instead.
func (*GetSpaceshipsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_spaceship_proto_rawDescGZIP(), []int{2}
}

func (x *GetSpaceshipsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSpaceshipsRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *GetSpaceshipsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetSpaceshipsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spaceships []*Spaceship `protobuf:"bytes,1,rep,name=spaceships,proto3" json:"spaceships,omitempty"`
}

func (x *GetSpaceshipsResponse) Reset() {
	*x = GetSpaceshipsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_spaceship_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpaceshipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpaceshipsResponse) ProtoMessage() {}

func (x *GetSpaceshipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_spaceship_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpaceshipsResponse.ProtoReflect.Descriptor instead.
func (*GetSpaceshipsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_spaceship_proto_rawDescGZIP(), []int{3}
}

func (x *GetSpaceshipsResponse) GetSpaceships() []*Spaceship {
	if x != nil {
		return x.Spaceships
	}
	return nil
}

type GetSpaceshipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetSpaceshipRequest) Reset() {
	*x = GetSpaceshipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_spaceship_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpaceshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpaceshipRequest) ProtoMessage() {}

func (x *GetSpaceshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_spaceship_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpaceshipRequest.ProtoReflect.Descriptor instead.
func (*GetSpaceshipRequest) Descriptor() ([]byte, []int) {
	return file_grpc_spaceship_proto_rawDescGZIP(), []int{4}
}

func (x *GetSpaceshipRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSpaceshipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spaceship *Spaceship `protobuf:"bytes,1,opt,name=spaceship,proto3" json:"spaceship,omitempty"`
}

func (x *GetSpaceshipResponse) Reset() {
	*x = GetSpaceshipResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_spaceship_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpaceshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpaceshipResponse) ProtoMessage() {}

func (x *GetSpaceshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_spaceship_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpaceshipResponse.ProtoReflect.Descriptor instead.
func (*GetSpaceshipResponse) Descriptor() ([]byte, []int) {
	return file_grpc_spaceship_proto_rawDescGZIP(), []int{5}
}

func (x *GetSpaceshipResponse) GetSpaceship() *Spaceship {
	if x != nil {
		return x.Spaceship
	}
	return nil
}

type UpdateSpaceshipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64                              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string                             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Class    string                             `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	Crew     int64                              `protobuf:"varint,4,opt,name=crew,proto3" json:"crew,omitempty"`
	ImageUrl string                             `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Value    float64                            `protobuf:"fixed64,6,opt,name=value,proto3" json:"value,omitempty"`
	Status   string                             `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Armament []*UpdateSpaceshipRequest_Armament `protobuf:"bytes,8,rep,name=armament,proto3" json:"armament,omitempty"`
}

func (x *UpdateSpaceshipRequest) Reset() {
	*x = UpdateSpaceshipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_spaceship_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSpaceshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSpaceshipRequest) ProtoMessage() {}

func (x *UpdateSpaceshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_spaceship_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSpaceshipRequest.ProtoReflect.Descriptor instead.
func (*UpdateSpaceshipRequest) Descriptor() ([]byte, []int) {
	return file_grpc_spaceship_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSpaceshipRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSpaceshipRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSpaceshipRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *UpdateSpaceshipRequest) GetCrew() int64 {
	if x != nil {
		return x.Crew
	}
	return 0
}

func (x *UpdateSpaceshipRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *UpdateSpaceshipRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *UpdateSpaceshipRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateSpaceshipRequest) GetArmament() []*UpdateSpaceshipRequest_Armament {
	if x != nil {
		return x.Armament
	}
	return nil
}

type UpdateSpaceshipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spaceship *Spaceship `protobuf:"bytes,1,opt,name=spaceship,proto3" json:"spaceship,omitempty"`
}

func (x *UpdateSpaceshipResponse) Reset() {
	*x = UpdateSpaceshipResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_spaceship_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSpaceshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSpaceshipResponse) ProtoMessage() {}

func (x *UpdateSpaceshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_spaceship_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSpaceshipResponse.ProtoReflect.Descriptor instead.
func (*UpdateSpaceshipResponse) Descriptor() ([]byte, []int) {
	return file_grpc_spaceship_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSpaceshipResponse) GetSpaceship() *Spaceship {
	if x != nil {
		return x.Spaceship
	}
	return nil
}

type DeleteSpaceshipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteSpaceshipRequest) Reset() {
	*x = DeleteSpaceshipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_spaceship_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSpaceshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSpaceshipRequest) ProtoMessage() {}

func (x *DeleteSpaceshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_spaceship_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSpaceshipRequest.ProtoReflect.Descriptor instead.
func (*DeleteSpaceshipRequest) Descriptor() ([]byte, []int) {
	return file_grpc_spaceship_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSpaceshipRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteSpaceshipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteSpaceshipResponse) Reset() {
	*x = DeleteSpaceshipResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_spaceship_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSpaceshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSpaceshipResponse) ProtoMessage() {}

func (x *DeleteSpaceshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_spaceship_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSpaceshipResponse.ProtoReflect.Descriptor instead.
func (*DeleteSpaceshipResponse) Descriptor() ([]byte, []int) {
	return file_grpc_spaceship_proto_rawDescGZIP(), []int{9}
}

type Spaceship struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Class    string                `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	Crew     int64                 `protobuf:"varint,4,opt,name=crew,proto3" json:"crew,omitempty"`
	ImageUrl string                `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Value    float64               `protobuf:"fixed64,6,opt,name=value,proto3" json:"value,omitempty"`
	Status   string                `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Armament []*Spaceship_Armament `protobuf:"bytes,8,rep,name=armament,proto3" json:"armament,omitempty"`
}

func (x *Spaceship) Reset() {
	*x = Spaceship{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_spaceship_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spaceship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spaceship) ProtoMessage() {}

func (x *Spaceship) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_spaceship_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spaceship.ProtoReflect.Descriptor instead.
func (*Spaceship) Descriptor() ([]byte, []int) {
	return file_grpc_spaceship_proto_rawDescGZIP(), []int{10}
}

func (x *Spaceship) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Spaceship) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Spaceship) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *Spaceship) GetCrew() int64 {
	if x != nil {
		return x.Crew
	}
	return 0
}

func (x *Spaceship) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Spaceship) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Spaceship) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Spaceship) GetArmament() []*Spaceship_Armament {
	if x != nil {
		return x.Armament
	}
	return nil
}

type CreateSpaceshipRequest_Armament struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title    string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Quantity int64  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *CreateSpaceshipRequest_Armament) Reset() {
	*x = CreateSpaceshipRequest_Armament{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_spaceship_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSpaceshipRequest_Armament) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpaceshipRequest_Armament) ProtoMessage() {}

func (x *CreateSpaceshipRequest_Armament) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_spaceship_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpaceshipRequest_Armament.ProtoReflect.Descriptor instead.
func (*CreateSpaceshipRequest_Armament) Descriptor() ([]byte, []int) {
	return file_grpc_spaceship_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateSpaceshipRequest_Armament) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSpaceshipRequest_Armament) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateSpaceshipRequest_Armament struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title    string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Quantity int64  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *UpdateSpaceshipRequest_Armament) Reset() {
	*x = UpdateSpaceshipRequest_Armament{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_spaceship_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSpaceshipRequest_Armament) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSpaceshipRequest_Armament) ProtoMessage() {}

func (x *UpdateSpaceshipRequest_Armament) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_spaceship_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSpaceshipRequest_Armament.ProtoReflect.Descriptor instead.
func (*UpdateSpaceshipRequest_Armament) Descriptor() ([]byte, []int) {
	return file_grpc_spaceship_proto_rawDescGZIP(), []int{6, 0}
}

func (x *UpdateSpaceshipRequest_Armament) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateSpaceshipRequest_Armament) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Spaceship_Armament struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title    string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Quantity int64  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *Spaceship_Armament) Reset() {
	*x = Spaceship_Armament{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_spaceship_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spaceship_Armament) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spaceship_Armament) ProtoMessage() {}

func (x *Spaceship_Armament) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_spaceship_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spaceship_Armament.ProtoReflect.Descriptor instead.
func (*Spaceship_Armament) Descriptor() ([]byte, []int) {
	return file_grpc_spaceship_proto_rawDescGZIP(), []int{10, 0}
}

func (x *Spaceship_Armament) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Spaceship_Armament) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_grpc_spaceship_proto protoreflect.FileDescriptor

var file_grpc_spaceship_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69,
	0x70, 0x22, 0xa7, 0x02, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x72, 0x65, 0x77, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x72, 0x65, 0x77, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x46, 0x0a, 0x08, 0x61, 0x72, 0x6d, 0x61, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73,
	0x68, 0x69, 0x70, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73,
	0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x72, 0x6d, 0x61, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x08, 0x61, 0x72, 0x6d, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x3c, 0x0a,
	0x08, 0x41, 0x72, 0x6d, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x4d, 0x0a, 0x17, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73,
	0x68, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x52,
	0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x22, 0x58, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x4d, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x73, 0x68, 0x69, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a,
	0x0a, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x52, 0x0a, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68,
	0x69, 0x70, 0x73, 0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73,
	0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4a, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69,
	0x70, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x52, 0x09, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x22, 0xb7, 0x02, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x72, 0x65, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x72, 0x65, 0x77, 0x12,
	0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x46, 0x0a, 0x08, 0x61, 0x72,
	0x6d, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x41, 0x72, 0x6d, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x61, 0x72, 0x6d, 0x61, 0x6d, 0x65,
	0x6e, 0x74, 0x1a, 0x3c, 0x0a, 0x08, 0x41, 0x72, 0x6d, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x22, 0x4d, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73,
	0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x73, 0x68, 0x69, 0x70, 0x52, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x22,
	0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68,
	0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x9d, 0x02, 0x0a, 0x09, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68,
	0x69, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x72, 0x65, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x72, 0x65, 0x77,
	0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x39, 0x0a, 0x08, 0x61,
	0x72, 0x6d, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73,
	0x68, 0x69, 0x70, 0x2e, 0x41, 0x72, 0x6d, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x61, 0x72,
	0x6d, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x3c, 0x0a, 0x08, 0x41, 0x72, 0x6d, 0x61, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x32, 0xcf, 0x03, 0x0a, 0x10, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68,
	0x69, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5a, 0x0a, 0x0f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x12, 0x21, 0x2e, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x73, 0x68, 0x69, 0x70, 0x73, 0x12, 0x1f, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68,
	0x69, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73,
	0x68, 0x69, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x12, 0x1e, 0x2e, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a,
	0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69,
	0x70, 0x12, 0x21, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x0f, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x12, 0x21, 0x2e,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x31, 0x5a, 0x2f, 0x69, 0x6d, 0x70, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x2d, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2d, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f,
	0x72, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x61, 0x6e, 0x67, 0x73, 0x2f, 0x67, 0x6f, 0x2f,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x68, 0x69, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_grpc_spaceship_proto_rawDescOnce sync.Once
	file_grpc_spaceship_proto_rawDescData = file_grpc_spaceship_proto_rawDesc
)

func file_grpc_spaceship_proto_rawDescGZIP() []byte {
	file_grpc_spaceship_proto_rawDescOnce.Do(func() {
		file_grpc_spaceship_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_spaceship_proto_rawDescData)
	})
	return file_grpc_spaceship_proto_rawDescData
}

var file_grpc_spaceship_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_grpc_spaceship_proto_goTypes = []interface{}{
	(*CreateSpaceshipRequest)(nil),          // 0: spaceship.CreateSpaceshipRequest
	(*CreateSpaceshipResponse)(nil),         // 1: spaceship.CreateSpaceshipResponse
	(*GetSpaceshipsRequest)(nil),            // 2: spaceship.GetSpaceshipsRequest
	(*GetSpaceshipsResponse)(nil),           // 3: spaceship.GetSpaceshipsResponse
	(*GetSpaceshipRequest)(nil),             // 4: spaceship.GetSpaceshipRequest
	(*GetSpaceshipResponse)(nil),            // 5: spaceship.GetSpaceshipResponse
	(*UpdateSpaceshipRequest)(nil),          // 6: spaceship.UpdateSpaceshipRequest
	(*UpdateSpaceshipResponse)(nil),         // 7: spaceship.UpdateSpaceshipResponse
	(*DeleteSpaceshipRequest)(nil),          // 8: spaceship.DeleteSpaceshipRequest
	(*DeleteSpaceshipResponse)(nil),         // 9: spaceship.DeleteSpaceshipResponse
	(*Spaceship)(nil),                       // 10: spaceship.Spaceship
	(*CreateSpaceshipRequest_Armament)(nil), // 11: spaceship.CreateSpaceshipRequest.Armament
	(*UpdateSpaceshipRequest_Armament)(nil), // 12: spaceship.UpdateSpaceshipRequest.Armament
	(*Spaceship_Armament)(nil),              // 13: spaceship.Spaceship.Armament
}
var file_grpc_spaceship_proto_depIdxs = []int32{
	11, // 0: spaceship.CreateSpaceshipRequest.armament:type_name -> spaceship.CreateSpaceshipRequest.Armament
	10, // 1: spaceship.CreateSpaceshipResponse.spaceship:type_name -> spaceship.Spaceship
	10, // 2: spaceship.GetSpaceshipsResponse.spaceships:type_name -> spaceship.Spaceship
	10, // 3: spaceship.GetSpaceshipResponse.spaceship:type_name -> spaceship.Spaceship
	12, // 4: spaceship.UpdateSpaceshipRequest.armament:type_name -> spaceship.UpdateSpaceshipRequest.Armament
	10, // 5: spaceship.UpdateSpaceshipResponse.spaceship:type_name -> spaceship.Spaceship
	13, // 6: spaceship.Spaceship.armament:type_name -> spaceship.Spaceship.Armament
	0,  // 7: spaceship.SpaceshipService.CreateSpaceship:input_type -> spaceship.CreateSpaceshipRequest
	2,  // 8: spaceship.SpaceshipService.GetSpaceships:input_type -> spaceship.GetSpaceshipsRequest
	4,  // 9: spaceship.SpaceshipService.GetSpaceship:input_type -> spaceship.GetSpaceshipRequest
	6,  // 10: spaceship.SpaceshipService.UpdateSpaceship:input_type -> spaceship.UpdateSpaceshipRequest
	8,  // 11: spaceship.SpaceshipService.DeleteSpaceship:input_type -> spaceship.DeleteSpaceshipRequest
	1,  // 12: spaceship.SpaceshipService.CreateSpaceship:output_type -> spaceship.CreateSpaceshipResponse
	3,  // 13: spaceship.SpaceshipService.GetSpaceships:output_type -> spaceship.GetSpaceshipsResponse
	5,  // 14: spaceship.SpaceshipService.GetSpaceship:output_type -> spaceship.GetSpaceshipResponse
	7,  // 15: spaceship.SpaceshipService.UpdateSpaceship:output_type -> spaceship.UpdateSpaceshipResponse
	9,  // 16: spaceship.SpaceshipService.DeleteSpaceship:output_type -> spaceship.DeleteSpaceshipResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_grpc_spaceship_proto_init() }
func file_grpc_spaceship_proto_init() {
	if File_grpc_spaceship_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_spaceship_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSpaceshipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_spaceship_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSpaceshipResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_spaceship_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpaceshipsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_spaceship_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpaceshipsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_spaceship_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpaceshipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_spaceship_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpaceshipResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_spaceship_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSpaceshipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_spaceship_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSpaceshipResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_spaceship_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSpaceshipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_spaceship_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSpaceshipResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_spaceship_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Spaceship); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_spaceship_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSpaceshipRequest_Armament); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_spaceship_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSpaceshipRequest_Armament); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_spaceship_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Spaceship_Armament); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_spaceship_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_spaceship_proto_goTypes,
		DependencyIndexes: file_grpc_spaceship_proto_depIdxs,
		MessageInfos:      file_grpc_spaceship_proto_msgTypes,
	}.Build()
	File_grpc_spaceship_proto = out.File
	file_grpc_spaceship_proto_rawDesc = nil
	file_grpc_spaceship_proto_goTypes = nil
	file_grpc_spaceship_proto_depIdxs = nil
}
